import {getDocument,GlobalWorkerOptions} from 'pdfjs-dist';
import {analyzeDocuments} from '../lib/readiness.js';
GlobalWorkerOptions.workerSrc='/assets/pdf.worker.min.mjs';
const form=document.querySelector('#document-check');let report;
const download=(name,text,type)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
async function extract(file,kind){
 if(!file||file.size>15*1024*1024||file.size<5)throw new Error('Choose a PDF under 15 MB for each document.');
 const data=new Uint8Array(await file.arrayBuffer());if(new TextDecoder().decode(data.slice(0,5))!=='%PDF-')throw new Error('File signature is not PDF.');
 const task=getDocument({data,cMapUrl:"/assets/cmaps/",cMapPacked:true,standardFontDataUrl:"/assets/standard_fonts/",wasmUrl:"/assets/wasm/",isEvalSupported:false,disableFontFace:true,useSystemFonts:false});
 try{const pdf=await task.promise;if(pdf.numPages>250)throw new Error('Maximum 250 pages per PDF. Use the relevant public schedules.');const pages=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);const content=await page.getTextContent();pages.push({page:n,text:content.items.map(x=>x.str||'').join(' ')});page.cleanup();}if(pages.reduce((a,p)=>a+p.text.trim().length,0)<100)throw new Error(`${kind}: searchable text unavailable. A scanned PDF requires OCR and human review.`);return {kind,name:file.name,pages};}finally{await task.destroy();}
}
form?.addEventListener('submit',async e=>{e.preventDefault();const status=document.querySelector('#doc-status'),button=form.querySelector('button');button.disabled=true;report=null;document.querySelector('#document-results').hidden=true;status.textContent='Reading searchable text locally. Keep this tab open.';try{const docs=[];docs.push(await extract(form.feeSchedule.files[0],'Fee schedule'));docs.push(await extract(form.acfr.files[0],'ACFR'));const matrix=analyzeDocuments(docs);report={schemaVersion:1,tool:'CivicReconcile public-document readiness',generatedAt:new Date().toISOString(),basis:'Keyword context only; no liability, compliance, fund-mismatch or recovery determination',documents:docs.map(d=>({kind:d.kind,name:d.name,pages:d.pages.length})),matrix};const root=document.querySelector('#matrix');root.replaceChildren();for(const item of matrix){const card=document.createElement('article');card.className='card';const h=document.createElement('h3');h.textContent=item.label;const p=document.createElement('p');p.textContent=item.status==='CONTEXT_LOCATED'?'Context located — verify with staff':'Not located in supplied text — obtain supporting records';const details=document.createElement('p');details.textContent=item.next;card.append(h,p,details);for(const hit of item.hits){const line=document.createElement('p');line.className='fine';line.textContent=`${hit.document}, page ${hit.page}: ${hit.excerpt}`;card.append(line);}root.append(card);}document.querySelector('#document-results').hidden=false;status.textContent='Check complete. Files stayed in this browser. No risk or recovery claim was calculated.';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
document.querySelector('#download-readiness')?.addEventListener('click',()=>{if(report)download('civicreconcile-readiness.json',JSON.stringify(report,null,2),'application/json');});
document.querySelector('#clear-documents')?.addEventListener('click',()=>{form.reset();report=null;document.querySelector('#matrix').replaceChildren();document.querySelector('#document-results').hidden=true;document.querySelector('#doc-status').textContent='Files and results cleared from this tab.';});
